name: econflux
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - geopandas
  - resipy
  - emagpy
  - pip
  - pip:
      - hydrostats
      - hydroeval
      - pysymlog
